name: readymadeGroceryApp
description: Grocery user app

version: 2.2.2+32

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  getflutter: ^1.0.11
  shared_preferences: ^0.5.3+4
  pin_entry_text_field: ^0.1.3
  location: ^3.0.1
  intl: ^0.16.1
  http: ^0.12.0+2
  sentry: ^2.2.0
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.3+1
  async_loader: ^0.1.2
  google_maps_flutter: ^0.5.25+3
  socket_io_client: ^0.9.9
  onesignal_flutter: ^2.4.1
  flutter_rating_bar: ^3.0.1+1
  dotted_border: ^1.0.5
  flutter_svg: ^0.18.0
  pagination: ^0.1.0
  geocoder: ^0.2.1
  image: ^2.1.4
  pull_to_refresh: ^1.5.7
  url_launcher: ^5.4.5
  flutter_map_picker: ^0.1.2
  stripe_payment: ^1.0.7
  flutter_dotenv: ^2.1.0
  http_interceptor: ^0.3.2
  fluttertoast: ^7.0.2
  flutter_html: ^1.0.2
  share: ^0.6.4+3
  device_info: ^0.4.2+6
  cached_network_image: ^2.2.0+1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test:
  screenshots:
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"

flutter:
  uses-material-design: true

  fonts:
    - family: icomoon
      fonts:
        - asset: lib/assets/fonts/icomoon.ttf

    - family: "BarlowBold"
      fonts:
        - asset: lib/assets/fonts/Barlow-Bold.ttf
          weight: 400

    - family: "BarlowMedium"
      fonts:
        - asset: lib/assets/fonts/Barlow-Medium.ttf
          weight: 400

    - family: "BarlowRegular"
      fonts:
        - asset: lib/assets/fonts/Barlow-Regular.ttf
          weight: 400

    - family: "BarlowSemiBold"
      fonts:
        - asset: lib/assets/fonts/Barlow-SemiBold.ttf
          weight: 400

    - family: "OswaldBold"
      fonts:
        - asset: lib/assets/fonts/oswaldBold.ttf
          weight: 400

    - family: "FuturaBold"
      fonts:
        - asset: lib/assets/fonts/futuraBold.otf
          weight: 400

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - lib/assets/images/profile.png
    - lib/assets/images/product.png
    - lib/assets/images/thank-you.png
    - lib/assets/images/badge.png
    - lib/assets/images/no-orders.png
    - lib/assets/images/wallet.png
    - lib/assets/images/walleticon.png
    - lib/assets/images/rate.png
    - lib/assets/images/profileIcon.png

    - lib/assets/icons/tick.svg
    - lib/assets/icons/editt.svg
    - lib/assets/icons/add1.svg

    - lib/assets/icons/sale.png
    - lib/assets/icons/Home.png
    - lib/assets/icons/products.png
    - lib/assets/icons/location.png
    - lib/assets/icons/fav.png
    - lib/assets/icons/chat.png
    - lib/assets/icons/about.png
    - lib/assets/icons/lg.png
    - lib/assets/icons/categories.png
    - lib/assets/icons/deals.png
    - lib/assets/icons/history.png
    - lib/assets/icons/tc.png
    - lib/assets/icons/share.png
    - lib/assets/icons/red.png
    - lib/assets/icons/green.png

    - lib/assets/splash.png
    - lib/assets/logo.png
