name: grocery_pro
description: A new Flutter project.

version: 1.0.1+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  getflutter: ^1.0.11
  shared_preferences: ^0.5.3+4
  pin_entry_text_field: ^0.1.3
  location: ^2.3.5
  intl: ^0.16.1
  http: ^0.12.0+2
  sentry: ^2.2.0
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.3+1
  async_loader: ^0.1.2
  google_map_location_picker: ^3.2.1+2
  google_maps_flutter: ^0.5.25+3
  socket_io_client: ^0.9.9
  onesignal_flutter: ^2.3.4
  flutter_rating_bar: ^3.0.1+1
  dotted_border: ^1.0.5
  flutter_svg: ^0.17.4

  geocoder: ^0.2.1
  image: ^2.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: icomoon
      fonts:
        - asset: lib/assets/fonts/icomoon.ttf


    - family: 'BarlowBold'
      fonts:   
        - asset: lib/assets/fonts/Barlow-Bold.ttf
          weight: 400

    - family: 'BarlowMedium'
      fonts:   
        - asset: lib/assets/fonts/Barlow-Medium.ttf
          weight: 400

    - family: 'BarlowRegular'
      fonts:   
        - asset: lib/assets/fonts/Barlow-Regular.ttf
          weight: 400
          
    - family: 'BarlowSemiBold'
      fonts:   
        - asset: lib/assets/fonts/Barlow-SemiBold.ttf
          weight: 400  


  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/icons/Group.png
    - lib/assets/icons/cross.png
    - lib/assets/images/apple.png
    - lib/assets/images/orange.png
    - lib/assets/icons/rupee.png
    - lib/assets/images/grape.png
    - lib/assets/images/strawberry.png
    - lib/assets/images/avocado.png
    - lib/assets/images/cherry.png
    - lib/assets/images/amul.png
    - lib/assets/images/profile.png
    - lib/assets/icons/edit.svg
    - lib/assets/images/creditcard.png
    - lib/assets/images/white.png
    - lib/assets/images/product.png
    - lib/assets/icons/logo.png
    - lib/assets/images/mastercard.png
    - lib/assets/icons/mastercard-logo.png
    - lib/assets/images/visa.png
    - lib/assets/images/thank-you.png
    - lib/assets/images/spinner.gif
    - lib/assets/images/badge.png

    - lib/assets/images/no-orders.png
    - lib/assets/icons/addbtn.png
    - lib/assets/icons/minus.png

    - lib/assets/icons/sale.png
    - lib/assets/icons/edit.png
    - lib/assets/icons/logout.png
    - lib/assets/icons/menu.png
    - lib/assets/icons/delete.png
    - lib/assets/icons/add.png
    - lib/assets/icons/minus.svg
    - lib/assets/icons/plus.svg
    - lib/assets/icons/confirm.png
    - lib/assets/icons/tick.svg
    - lib/assets/icons/editt.svg
    - lib/assets/icons/lgout.svg

    - lib/assets/splash.png