name: grocery_pro
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  getflutter: ^1.0.3
  shared_preferences: ^0.5.3+4
  pin_entry_text_field: ^0.1.3
  country_pickers: ^1.1.0
  flappy_search_bar: ^1.7.2
  search_widget: ^1.0.1
  badges: ^1.1.0
  flutter_rating_bar: ^3.0.1+1
  flutter_range_slider: ^1.4.0
  # flutter_alert: ^1.0.3
  http: ^0.12.0+2
  sentry: ^2.2.0
  # firebase_core: ^0.4.3+2
  # firebase_auth: ^0.15.4
  # google_sign_in: ^4.1.1
  # cloud_firestore: ^0.13.0+1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
    
  fonts:
    - family: icomoon
      fonts:   
        - asset: lib/fonts/icomoon.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/icons/Group.png
    - lib/assets/icons/cross.png
    - lib/assets/images/apple.png
    - lib/assets/images/orange.png
    - lib/assets/icons/rupee.png
    - lib/assets/images/grape.png
    - lib/assets/images/strawberry.png
    - lib/assets/images/avocado.png
    - lib/assets/images/cherry.png
    - lib/assets/images/amul.png
    - lib/assets/images/profile.png
    - lib/assets/icons/edit.svg
    - lib/assets/images/creditcard.png
    - lib/assets/images/white.png
    - lib/assets/images/product.png
    - lib/assets/icons/logo.png
    - lib/assets/images/mastercard.png
















  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
