name: readymadeGroceryApp
description: Grocery user app

version: 3.1.3+36

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  getwidget: ^2.0.1-nullsafety.4
  shared_preferences: ^2.0.5
  #  pin_entry_text_field: ^0.1.3
  pin_code_fields: ^7.0.0
  location: ^4.1.1
  intl: ^0.17.0
  http: ^0.13.1
  sentry: ^4.0.6
  cupertino_icons: ^1.0.2
  image_picker: ^0.7.3
  google_maps_flutter: ^2.0.1
  socket_io_client: ^2.0.0-beta.3-nullsafety.0
  onesignal_flutter: ^3.0.0
  flutter_rating_bar: ^4.0.0
  dotted_border: ^2.0.0-nullsafety.0
  flutter_svg: ^0.21.0-nullsafety.0
  #  pagination: ^0.1.0
  #  geocoder: ^0.2.1
  geocode: 1.0.1
  image: ^3.0.2
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.0.2
  #  flutter_map_picker: ^0.1.2
  google_maps_place_picker: ^2.0.0-nullsafety.3
  #  stripe_payment: ^1.0.11
  flutter_dotenv: ^4.0.0-nullsafety.0
  http_interceptor: ^0.4.1
  fluttertoast: ^8.0.3
  flutter_html: ^2.0.0-nullsafety.0
  share: ^2.0.1
  device_info: ^2.0.0
  cached_network_image: ^3.0.0-nullsafety
  connectivity: ^3.0.3
  provider: ^5.0.0
  photo_view: ^0.11.1
  webview_flutter: ^2.0.2
  flutter_datetime_picker: ^1.5.0
  flutter_date_picker_timeline: ^0.3.1
  flutter_launcher_icons: ^0.9.0
  #  screenshots:
  screenshot: ^1.2.0
  flutter_localizations:
    sdk: flutter

dependency_overrides:
  args:
  archive:
  file:
  crypto:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test:

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"

flutter:
  uses-material-design: true

  fonts:
    - family: icomoon
      fonts:
        - asset: lib/assets/fonts/icomoon.ttf

    - family: "BarlowBold"
      fonts:
        - asset: lib/assets/fonts/Barlow-Bold.ttf
          weight: 400

    - family: "BarlowMedium"
      fonts:
        - asset: lib/assets/fonts/Barlow-Medium.ttf
          weight: 400

    - family: "BarlowRegular"
      fonts:
        - asset: lib/assets/fonts/Barlow-Regular.ttf
          weight: 400

    - family: "BarlowSemiBold"
      fonts:
        - asset: lib/assets/fonts/Barlow-SemiBold.ttf
          weight: 400

    - family: "OswaldBold"
      fonts:
        - asset: lib/assets/fonts/oswaldBold.ttf
          weight: 400

    - family: "FuturaBold"
      fonts:
        - asset: lib/assets/fonts/futuraBold.otf
          weight: 400

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - lib/assets/images/profile.png
    - lib/assets/images/product.png
    - lib/assets/images/thank-you.png
    - lib/assets/images/badge.png
    - lib/assets/images/no-orders.png
    - lib/assets/images/wallet.png
    - lib/assets/images/walleticon.png
    - lib/assets/images/rate.png
    - lib/assets/images/profileIcon.png
    - lib/assets/images/failed.png
    - lib/assets/images/ref.png
    - lib/assets/images/copy.png
    - lib/assets/images/wapp.png
    - lib/assets/images/sms.png
    - lib/assets/icons/map.png
    - lib/assets/images/copylink.png
    - lib/assets/images/addMoney.png
    - lib/assets/images/walletImage.png

    - lib/assets/icons/tick.svg
    - lib/assets/icons/editt.svg
    - lib/assets/icons/add1.svg
    - lib/assets/icons/Refer.svg

    - lib/assets/icons/sale.png
    - lib/assets/icons/Home.png
    - lib/assets/icons/products.png
    - lib/assets/icons/location.png
    - lib/assets/icons/fav.png
    - lib/assets/icons/chat.png
    - lib/assets/icons/about.png
    - lib/assets/icons/lg.png
    - lib/assets/icons/categories.png
    - lib/assets/icons/deals.png
    - lib/assets/icons/history.png
    - lib/assets/icons/tc.png
    - lib/assets/icons/share.png
    - lib/assets/icons/red.png
    - lib/assets/icons/green.png
    - lib/assets/icons/back.png
    - lib/assets/icons/front.png
    - lib/assets/icons/refer.png
    - lib/assets/icons/subscription_list.png

    - lib/assets/splash.png
    - lib/assets/logo.png