name: readymadeGroceryApp
description: Grocery user app

version: 3.1.7+40

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  getwidget:
    git:
      url: https://github.com/ionicfirebaseapp/getwidget.git
  shared_preferences: ^2.0.6
  pin_code_fields: ^7.2.0
  geolocator: ^8.2.0
  intl: ^0.17.0
  http: ^0.13.3
  sentry: ^6.3.0
  cupertino_icons: ^1.0.3
  image_picker: ^0.8.1+3
  google_maps_flutter: ^2.0.6
  socket_io_client: ^1.0.1
  onesignal_flutter: ^3.2.3
  flutter_rating_bar: ^4.0.0
  dotted_border: ^2.0.0
  flutter_svg: ^1.0.3
  geocoding: ^2.0.1
  image: ^3.0.2
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.0.9
  flutter_config: ^2.0.0
  http_interceptor: ^1.0.0
  fluttertoast: ^8.0.7
  flutter_html: ^3.0.0-alpha.2
  share: ^2.0.4
  cached_network_image: ^3.0.0
  connectivity: ^3.0.6
  provider: ^6.0.2
  photo_view: ^0.13.0
  flutter_stripe: ^2.0.2
  google_maps_webservice: ^0.0.20-nullsafety.5
  razorpay_flutter: ^1.2.7
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
  go_sell_sdk_flutter: ^2.1.1
  webview_flutter: ^3.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.16.8
  screenshot: ^1.2.1
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"

flutter:
  uses-material-design: true

  fonts:
    - family: icomoon
      fonts:
        - asset: lib/assets/fonts/icomoon.ttf

    - family: "BarlowBold"
      fonts:
        - asset: lib/assets/fonts/Barlow-Bold.ttf
          weight: 400

    - family: "BarlowMedium"
      fonts:
        - asset: lib/assets/fonts/Barlow-Medium.ttf
          weight: 400

    - family: "BarlowRegular"
      fonts:
        - asset: lib/assets/fonts/Barlow-Regular.ttf
          weight: 400

    - family: "BarlowSemiBold"
      fonts:
        - asset: lib/assets/fonts/Barlow-SemiBold.ttf
          weight: 400

    - family: "OswaldBold"
      fonts:
        - asset: lib/assets/fonts/oswaldBold.ttf
          weight: 400

    - family: "FuturaBold"
      fonts:
        - asset: lib/assets/fonts/futuraBold.otf
          weight: 400

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - lib/assets/images/profile.png
    - lib/assets/images/product.png
    - lib/assets/images/thank-you.png
    - lib/assets/images/badge.png
    - lib/assets/images/no-orders.png
    - lib/assets/images/wallet.png
    - lib/assets/images/walleticon.png
    - lib/assets/images/rate.png
    - lib/assets/images/profileIcon.png
    - lib/assets/images/failed.png
    - lib/assets/images/ref.png
    - lib/assets/images/copy.png
    - lib/assets/images/wapp.png
    - lib/assets/images/sms.png
    - lib/assets/icons/map.png
    - lib/assets/images/copylink.png
    - lib/assets/images/addMoney.png
    - lib/assets/images/walletImage.png
    - lib/assets/images/banner_bg.png

    - lib/assets/icons/tick.svg
    - lib/assets/icons/editt.svg
    - lib/assets/icons/add1.svg
    - lib/assets/icons/Refer.svg

    - lib/assets/icons/sale.png
    - lib/assets/icons/Home.png
    - lib/assets/icons/products.png
    - lib/assets/icons/location.png
    - lib/assets/icons/fav.png
    - lib/assets/icons/chat.png
    - lib/assets/icons/about.png
    - lib/assets/icons/lg.png
    - lib/assets/icons/categories.png
    - lib/assets/icons/deals.png
    - lib/assets/icons/history.png
    - lib/assets/icons/tc.png
    - lib/assets/icons/share.png
    - lib/assets/icons/red.png
    - lib/assets/icons/green.png
    - lib/assets/icons/back.png
    - lib/assets/icons/front.png
    - lib/assets/icons/refer.png
    - lib/assets/icons/subscription_list.png
    - lib/assets/icons/bell.png
    - lib/assets/icons/menu.png
    - lib/assets/icons/cat1.png
    - lib/assets/icons/cat2.png
    - lib/assets/icons/add.png
    - lib/assets/icons/minus.png
    - lib/assets/icons/heart.png
    - lib/assets/icons/banner1.png
    - lib/assets/icons/banner2.png
    - lib/assets/icons/dairymilk.png
    - lib/assets/icons/apple.png
    - lib/assets/icons/filter.png
    - lib/assets/icons/cancel.png
    - lib/assets/icons/search.png

    - lib/assets/splash.png
    - lib/assets/logo.png
